#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2015 OpenWrt.org

START=99

USE_PROCD=1
PROG=/usr/bin/antiblock

start_service() {	
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_append_param command -url https://antifilter.download/list/domains.lst
	procd_append_param command -file /root/new.txt
	procd_close_instance
}
