#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2015 OpenWrt.org

START=99

USE_PROCD=1

PROG=antiblock

start_service() {
	echo "Antiblock start"

	config_load "$PROG"

	local url
	local file1
	local route_IP
	local DNS_IP
	local DNS_port
	local listen_port

	config_get url args url
	config_get file1 args file
	config_get route_IP args route_IP
	config_get DNS_IP args DNS_IP
	config_get DNS_port args DNS_port
	config_get listen_port args listen_port

	procd_open_instance

	procd_set_param command "/usr/bin/$PROG"

	procd_set_param respawn
	procd_set_param stdout 1

	procd_append_param command -url "$url"
	procd_append_param command -file "$file1"
	procd_append_param command -route_IP "$route_IP"
	procd_append_param command -DNS_IP "$DNS_IP"
	procd_append_param command -DNS_port "$DNS_port"
	procd_append_param command -listen_port "$listen_port"

	procd_close_instance

	uci add_list dhcp.@dnsmasq[0].noresolv='1'
	uci set dhcp.@dnsmasq[0].rebind_protection='0'
	uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$listen_port
	
	uci set network.NAT=interface
	uci set network.NAT.proto='static'
	uci set network.NAT.device='antiblock'
	uci set network.NAT.ipaddr='10.7.1.1'
	uci set network.NAT.netmask='255.255.0.0'

	uci add network route
	uci set network.@route[-1].interface='VPN'
	uci set network.@route[-1].target='0.0.0.0/0'
	uci set network.@route[-1].table='2'

	uci add network rule
	uci set network.@rule[-1].src='10.7.128.0/17'
	uci set network.@rule[-1].lookup='2'

	uci add_list firewall.@zone[0].network='NAT'

	uci commit

	/etc/init.d/network restart
}

stop_service() {
	echo "Antiblock stop"

	config_load "$PROG"

	local listen_port

	config_get listen_port args listen_port

	uci del_list dhcp.@dnsmasq[0].noresolv='1'
	uci set dhcp.@dnsmasq[0].rebind_protection='1'
	uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#$listen_port
	
	uci delete network.@route[1]
	
	uci delete network.@rule[1]
	
	uci delete network.NAT
	
	uci del_list firewall.@zone[0].network='NAT'

	uci commit

	/etc/init.d/network restart
}
