#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2015 OpenWrt.org

START=99

USE_PROCD=1

PROG=antiblock

start_service() {
	echo "Antiblock start"

	config_load "$PROG"

	local url
	local file1
	local route_IP
	local DNS_IP
	local DNS_port
	local listen_port

	config_get url args url
	config_get file1 args file
	config_get route_IP args route_IP
	config_get DNS_IP args DNS_IP
	config_get DNS_port args DNS_port
	config_get listen_port args listen_port

	procd_open_instance

	procd_set_param command "/usr/bin/$PROG"

	procd_set_param respawn
	procd_set_param stdout 1

	procd_append_param command -url "$url"
	procd_append_param command -file "$file1"
	procd_append_param command -route_IP "$route_IP"
	procd_append_param command -DNS_IP "$DNS_IP"
	procd_append_param command -DNS_port "$DNS_port"
	procd_append_param command -listen_port "$listen_port"

	procd_close_instance

	uci add_list dhcp.@dnsmasq[0].noresolv='1'
	uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$listen_port
	uci commit

	/etc/init.d/dnsmasq restart
}

stop_service() {
	echo "Antiblock stop"

	config_load "$PROG"

	local listen_port

	config_get listen_port args listen_port

	uci del_list dhcp.@dnsmasq[0].noresolv='1'
	uci del_list dhcp.@dnsmasq[0].server=127.0.0.1#$listen_port
	uci commit

	/etc/init.d/dnsmasq restart
}
